export const queryKeys = {
  dashboard: {
    all: ['dashboard'] as const,
    overview: (range: string) => ['dashboard', 'overview', range] as const,
  },
  counts: ['admin', 'counts'] as const,
  billing: {
    all: ['billing'] as const,
    summary: ['billing', 'summary'] as const,
    plans: ['billing', 'plans'] as const,
    requests: (q: object) => ['billing', 'requests', q] as const,
    subscribers: (q: object) => ['billing', 'subscribers', q] as const,
    commissionPayments: (q: object) => ['billing', 'commission-payments', q] as const,
    ledger: (q: object) => ['billing', 'ledger', q] as const,
    bit: ['billing', 'bit'] as const,
    platform: ['billing', 'platform'] as const,
  },
  payments: {
    all: ['payments'] as const,
    summary: ['payments', 'summary'] as const,
    withdrawals: (q: object) => ['payments', 'withdrawals', q] as const,
    failed: (q: object) => ['payments', 'failed', q] as const,
  },
  offers: { all: ['offers'] as const, list: ['offers', 'list'] as const },
  ads: { all: ['ads'] as const, list: ['ads', 'list'] as const },
  craftsmen: { all: ['craftsmen'] as const, list: (q: object) => ['craftsmen', 'list', q] as const },
  tasks: {
    all: ['tasks'] as const,
    list: (q: object) => ['tasks', 'list', q] as const,
    detail: (id: string) => ['tasks', 'detail', id] as const,
  },
  disputes: { all: ['disputes'] as const, list: (q: object) => ['disputes', 'list', q] as const },
  reports: { all: ['reports'] as const, list: (q: object) => ['reports', 'list', q] as const },
  verification: { all: ['verification'] as const, queue: (q: object) => ['verification', 'queue', q] as const },
  users: { all: ['users'] as const, list: (q: object) => ['users', 'list', q] as const },
  team: ['admin', 'team'] as const,
  settings: {
    all: ['settings'] as const,
    platform: ['settings', 'platform'] as const,
    autoVerification: ['settings', 'auto-verification'] as const,
  },
  audit: { list: (q: object) => ['audit', 'list', q] as const },
  broadcasts: { all: ['broadcasts'] as const, list: (q: object) => ['broadcasts', 'list', q] as const },
  categories: { all: ['categories'] as const },
  analytics: (tf: string) => ['analytics', tf] as const,
  live: ['live-activity'] as const,
};
