import { ENV } from './env';

export const API_BASE_URL = ENV.API_BASE_URL;

export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me', // documented as missing but kept here as key
  },
  metrics: {
    list: '/admin/overview-stats',
    update: (id: string) => `/metrics/${id}`,
    categoryVolumes: '/metrics/category-volumes',
    pendingReports: '/metrics/pending-reports',
    verificationSubmissions: '/metrics/verification-submissions',
    cohortData: '/metrics/cohort-data',
  },
  tasks: {
    list: '/admin/tasks',
    freeze: (id: string) => `/admin/tasks/${id}/freeze`,
    unfreeze: (id: string) => `/admin/tasks/${id}/unfreeze`,
  },
  categories: {
    list: '/admin/categories',
    create: '/admin/categories',
    update: (id: string) => `/admin/categories/${id}`,
    subcategories: (catId: string) => `/admin/categories/${catId}/subcategories`,
    createSubcategory: (catId: string) => `/admin/categories/${catId}/subcategories`,
    updateVisibility: (id: string) => `/admin/categories/${id}/visibility`,
    subcategoryVisibility: (subId: string) => `/admin/categories/subcategories/${subId}/visibility`,
    fields: (id: string) => `/admin/categories/${id}/fields`,
    createField: (id: string) => `/admin/categories/${id}/fields`,
    toggleFieldRequired: (id: string) => `/admin/fields/${id}/toggle-required`,
    deleteField: (id: string) => `/admin/fields/${id}`,
    moveSubcategory: (id: string) => `/admin/categories/subcategories/${id}/move`,
  },
  craftsmen: {
    list: '/admin/craftsmen',
    suspend: (id: string) => `/admin/craftsmen/${id}/suspend`,
    unsuspend: (id: string) => `/admin/craftsmen/${id}/unsuspend`,
    ban: (id: string) => `/admin/craftsmen/${id}/ban`,
    toggleVerificationItem: (id: string) => `/admin/craftsmen/${id}/verify/item`,
  },
  payments: {
    summary: '/admin/payments/summary',
    plans: '/admin/payments/plans',
    failedTransactions: '/admin/payments',
    retryTransaction: (id: string) => `/admin/payments/failed-transactions/${id}/retry`,
    withdrawalRequests: '/admin/payments/withdrawal-requests',
    updateWithdrawalStatus: (id: string) => `/admin/payments/withdrawal-requests/${id}/status`,
  },
  systemSettings: '/admin/settings',
  admin: {
    overviewStats: '/admin/overview-stats',
    verificationQueue: '/admin/verification/queue',
    verificationModerate: '/admin/verification/moderate',
    craftsmen: '/admin/craftsmen',
    tasks: '/admin/tasks',
    disputes: '/admin/disputes',
    resolveDispute: (id: string) => `/admin/disputes/${id}/resolve`,
    payments: '/admin/payments',
    plans: '/admin/subscriptions/plans',
    subscribers: '/admin/subscriptions/subscribers',
    cancelSubscriber: (id: string) => `/admin/subscriptions/subscribers/${id}/cancel`,
    extendSubscriber: (id: string) => `/admin/subscriptions/subscribers/${id}/extend`,
    liveActivity: '/admin/live-activity',
    ads: '/admin/ads',
    deleteAd: (id: string) => `/admin/ads/${id}`,
    updateAdStatus: (id: string) => `/admin/ads/${id}/status`,
    promotions: '/admin/promotions',
    togglePromotion: (id: string) => `/admin/promotions/${id}/toggle`,
    deletePromotion: (id: string) => `/admin/promotions/${id}`,
    broadcasts: '/admin/notifications/broadcasts',
    sendBroadcast: '/admin/notifications/broadcast',
    deleteBroadcast: (id: string) => `/admin/notifications/broadcasts/${id}`,
    categories: '/admin/categories',
    deleteCategory: (id: string) => `/admin/categories/${id}`,
    subcategories: (id: string) => `/admin/categories/${id}/subcategories`,
    createSubcategory: (id: string) => `/admin/categories/${id}/subcategories`,
    deleteSubcategory: (subId: string) => `/admin/categories/subcategories/${subId}`,
    auditLogs: '/admin/audit-logs',
    reports: '/admin/reports',
    moderateReport: (id: string) => `/admin/reports/${id}/moderate`,
    cohort: '/admin/metrics/cohort',
    autoVerification: '/admin/settings/auto-verification',
    dispatchBackup: (id: string) => `/admin/tasks/${id}/dispatch-backup`,
    subscriptionRequests: '/admin/subscriptions/requests',
    approveSubscriptionRequest: (id: string) => `/admin/subscriptions/requests/${id}/approve`,
    rejectSubscriptionRequest: (id: string) => `/admin/subscriptions/requests/${id}/reject`,
    bitSettings: '/admin/subscriptions/bit-settings',
  },
  chat: {
    rooms: '/chatrooms',
    messages: (roomId: string) => `/chatrooms/${roomId}/messages`,
    sendMessage: (roomId: string) => `/chatrooms/${roomId}/messages`,
  },
  notifications: {
    list: '/notifications',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  }
};
export default API_ENDPOINTS;
